name:                mail-pool
version:             2.1.0
license:             MIT
author:              "Jappie Klooster"
maintainer:          "jappieklooster@hotmail.com"
copyright:           "2019 Jappie Klooster"
synopsis : "Preconfigured email connection pool on top of smtp."
description: "Email helper functions with some sane defaults such as a resource pool and cli support"
category: "Email"
github: jappeace/email-pool

extra-source-files:
- Readme.md
- LICENSE

ghc-options:
    - -Wall
    - -Wcompat
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
    - -Wincomplete-record-updates
    - -Widentities

# from https://lexi-lambda.github.io/blog/2018/02/10/an-opinionated-guide-to-haskell-in-2018/
default-extensions:
  # trivial
  - EmptyCase
  - FlexibleContexts
  - FlexibleInstances
  - InstanceSigs
  - MultiParamTypeClasses
  # only activated once used
  - LambdaCase
  - MultiWayIf
  - NamedFieldPuns
  - TupleSections
  # no cost deriving power
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveLift
  - DeriveTraversable
  - DerivingStrategies
  - GeneralizedNewtypeDeriving
  - StandaloneDeriving
  # used everywhere anyway
  - OverloadedStrings
  # ehh syntax
  - TypeApplications

dependencies:
- base >= 4.7 && < 5
- mime-mail >= 0.4.14 && < 0.5
- optparse-applicative >= 0.14.3.0 && < 0.15
- HaskellNet >=0.5.1 && < 0.6
- network >= 2.8.0.0 && < 3.0.0.0
- resource-pool >= 0.2.3.2 && < 0.3.0.0
- microlens >=0.4.10 && < 0.5.0
- HaskellNet-SSL >= 0.3.4.1 && < 0.4
- time >= 1.8.0.2 && < 1.9

library:
  source-dirs: src

executables:
  exe:
    main:                mail.hs
    source-dirs:         app
    dependencies:
    - mail-pool
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
